apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-k
spec:
  replicas: 1
  selector:
    matchLabels:
      name: camel-k
  template:
    metadata:
      labels:
        name: camel-k
    spec:
      containers:
        - name: camel-k
          image: docker.io/apache/camel-k:0.0.1-SNAPSHOT
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - camel-k
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "camel-k"
